name: 'Build and Notify' 
description: 'Composite action for building and notifying'

inputs:
  webhook-url:
    description: 'URL for Microsoft Teams webhook'
    required: true
  error-mention-id:
    description: 'ID for mentioning in case of error'
    required: true
  error-mention-name:
    description: 'Name for mentioning in case of error'
    required: true
  success-mention-id:
    description: 'ID for mentioning in case of success'
    required: true
  success-mention-name:
    description: 'Name for mentioning in case of success'
    required: true
  job-status:
    description: 'Status of the job (PASS or FAIL)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send notification to Microsoft Teams
      shell: bash
      run: |
        JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        echo "Received job status: ${{ inputs.job-status }}"
        
        # Check if the status is PASS
        if [[ "${{ inputs.job-status }}" == "PASS" ]]; then
          echo "Job status is PASS"
          status="PASS ✅"
          color="good"
          mentionedId="${{ inputs.success-mention-id }}"
          mentionedName="${{ inputs.success-mention-name }}"
        else
          # If not PASS, consider it as FAIL
          echo "Job status is FAIL"
          status="FAIL ❌"
          color="attention"
          mentionedId="${{ inputs.error-mention-id }}"
          mentionedName="${{ inputs.error-mention-name }}"
        fi
        
        payload='{
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "type": "AdaptiveCard",
                "body": [
                  {
                    "type": "TextBlock",
                    "text": "<at>'"$mentionedName"'</at>",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job Name:** Build and Notify",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Status:** '"$status"'",
                    "color": "'"$color"'"
                  }
                ],
                "msteams": {
                  "entities": [
                    {
                      "type": "mention",
                      "text": "<at>'"$mentionedName"'</at>",
                      "mentioned": {
                        "id": "'"$mentionedId"'",
                        "name": "'"$mentionedName"'"
                      }
                    }
                  ]
                }
              }
            }
          ]
        }'

        echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
