name: 'Build and Notify'
description: 'Composite action for building and notifying'

inputs:
  webhook-url:
    description: 'URL for Microsoft Teams webhook'
    required: true
  error-mention-id:
    description: 'ID for mentioning in case of error'
    required: true
  error-mention-name:
    description: 'Name for mentioning in case of error'
    required: true
  success-mention-id:
    description: 'ID for mentioning in case of success'
    required: true
  success-mention-name:
    description: 'Name for mentioning in case of success'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: echo "Building"

    - name: Test
      shell: bash
      run: echo "Testing"

    - name: Send notification to Microsoft Teams
      shell: bash
      run: |
        # Get the GitHub workflow run URL
        JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        # Determine the job status
        if [ -n "${{ steps.error }}" ]; then
          status="FAIL ❌"
          color="attention"
          mentionedId="${{ inputs.error-mention-id }}"
          mentionedName="${{ inputs.error-mention-name }}"
        else
          status="PASS ✅"
          color="good"
          mentionedId="${{ inputs.success-mention-id }}"
          mentionedName="${{ inputs.success-mention-name }}"
        fi
        
        # Generate the payload for the notification
        payload='{
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "type": "AdaptiveCard",
                "body": [
                  {
                    "type": "TextBlock",
                    "text": "<at>'"$mentionedName"'</at>",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job Name:** Build and Notify",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Status:** '"$status"'",
                    "color": "'"$color"'"
                  }
                ],
                "msteams": {
                  "entities": [
                    {
                      "type": "mention",
                      "text": "<at>'"$mentionedName"'</at>",
                      "mentioned": {
                        "id": "'"$mentionedId"'",
                        "name": "'"$mentionedName"'"
                      }
                    }
                  ]
                }
              }
            }
          ]
        }'
        
        # Send the payload to Microsoft Teams
        echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- "${{ inputs.webhook-url }}"
