name: 'Build and Notify'
description: 'Composite action for building and notifying'

inputs:
  webhook-url:
    description: 'URL for Microsoft Teams webhook'
    required: true
  error-mention-id:
    description: 'ID for mentioning in case of error'
    required: true
  error-mention-name:
    description: 'Name for mentioning in case of error'
    required: true
  success-mention-id:
    description: 'ID for mentioning in case of success'
    required: true
  success-mention-name:
    description: 'Name for mentioning in case of success'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set error flag if any step fails
      shell: bash
      id: error
      run: |
        if [ -n "$?" ]; then
          echo "Error occurred"
          exit 1
        fi

    - name: Get commit information
      shell: bash
      id: commit_info
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        echo "::set-output name=commit_hash::$COMMIT_HASH"
        echo "::set-output name=branch_name::$BRANCH_NAME"

    - name: Set success flag if all steps pass
      shell: bash
      id: success
      run: echo "All steps passed"

    - name: Send notification to Microsoft Teams
      run: |
        JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        if [ -n "${{ steps.error.outputs.result }}" ]; then
          status="FAIL ❌"
          color="attention"
          mentionedId="${{ inputs.error-mention-id }}"
          mentionedName="${{ inputs.error-mention-name }}"
        elif [ -n "${{ steps.success.outputs.result }}" ]; then
          status="PASS ✅"
          color="good"
          mentionedId="${{ inputs.success-mention-id }}"
          mentionedName="${{ inputs.success-mention-name }}"
        else
          status="UNKNOWN"
          color="default"
        fi
        
        COMMIT_HASH="${{ steps.commit_info.outputs.commit_hash }}"
        BRANCH_NAME="${{ steps.commit_info.outputs.branch_name }}"
        REPO_URL="[${{ github.repository }}](${{ github.event.repository.html_url }})"
        BUILD_NUMBER="${{ github.run_number }}"
        
        payload='{
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "type": "AdaptiveCard",
                "body": [
                  {
                    "type": "TextBlock",
                    "text": "<at>'"$mentionedName"'</at>",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job Name:** Build and Notify",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Status:** '"$status"'",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Repository URL:** '"$REPO_URL"'",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Build Number:** '"$BUILD_NUMBER"'",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Branch Name:** '"$BRANCH_NAME"'",
                    "color": "'"$color"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Latest Commit:** '"$COMMIT_HASH"'",
                    "color": "'"$color"'"
                  }
                ],
                "msteams": {
                  "entities": [
                    {
                      "type": "mention",
                      "text": "<at>'"$mentionedName"'</at>",
                      "mentioned": {
                        "id": "'"$mentionedId"'",
                        "name": "'"$mentionedName"'"
                      }
                    }
                  ]
                }
              }
            }
          ]
        }'

        echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
