name: New Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    env:
      ERROR_MENTION_ID: ${{ secrets.ERROR_MENTION_ID }}
      ERROR_MENTION_NAME: ${{ secrets.ERROR_MENTION_NAME }}
      SUCCESS_MENTION_ID: ${{ secrets.SUCCESS_MENTION_ID }}
      SUCCESS_MENTION_NAME: ${{ secrets.SUCCESS_MENTION_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse environment variables
        run: |
          ERROR_MENTION_ID=$(grep -Po '"ERROR_MENTION_ID": *\K"[^"]*"' env.json | tr -d '"')
          ERROR_MENTION_NAME=$(grep -Po '"ERROR_MENTION_NAME": *\K"[^"]*"' env.json | tr -d '"')
          SUCCESS_MENTION_ID=$(grep -Po '"SUCCESS_MENTION_ID": *\K"[^"]*"' env.json | tr -d '"')
          SUCCESS_MENTION_NAME=$(grep -Po '"SUCCESS_MENTION_NAME": *\K"[^"]*"' env.json | tr -d '"')
          echo "ERROR_MENTION_ID='${ERROR_MENTION_ID}'" >> .env
          echo "ERROR_MENTION_NAME='${ERROR_MENTION_NAME}'" >> .env
          echo "SUCCESS_MENTION_ID='${SUCCESS_MENTION_ID}'" >> .env
          echo "SUCCESS_MENTION_NAME='${SUCCESS_MENTION_NAME}'" >> .env

      - name: Print environment variables
        run: |
          source .env
          echo "ERROR_MENTION_ID: $ERROR_MENTION_ID"
          echo "ERROR_MENTION_NAME: $ERROR_MENTION_NAME"
          echo "SUCCESS_MENTION_ID: $SUCCESS_MENTION_ID"
          echo "SUCCESS_MENTION_NAME: $SUCCESS_MENTION_NAME"

      - name: Send notification to Microsoft Teams
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          error-mention-id: ${{ env.ERROR_MENTION_ID }}
          error-mention-name: ${{ env.ERROR_MENTION_NAME }}
          success-mention-id: ${{ env.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ env.SUCCESS_MENTION_NAME }}
