name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Notify
        uses: ./.github/actions/build_and_notify
        with:
          error-mention-id: ${{ env.GHA_Environment_Variables_ERROR_MENTION_ID }}
          error-mention-name: ${{ env.GHA_Environment_Variables_ERROR_MENTION_NAME }}
          success-mention-id: ${{ env.GHA_Environment_Variables_SUCCESS_MENTION_ID }}
          success-mention-name: ${{ env.GHA_Environment_Variables_SUCCESS_MENTION_NAME }}
