name: Simple Workflow   
  
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Job Status
        id: check_status
        run: |
          echo "Job status: success"
          if [ "success" == 'completed' ]; then
            if [ "" == 'success' ]; then
              echo "Job outcome: Success"
              echo "::set-output name=status::PASS"
            else
              echo "Job outcome: Failure"
              echo "::set-output name=status::FAIL"
            fi
          else
            echo "Job status: In Progress"
            echo "::set-output name=status::IN_PROGRESS"
          fi

      - name: Notify Build Status
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          error-mention-id: ${{ secrets.ERROR_MENTION_ID }}
          error-mention-name: ${{ secrets.ERROR_MENTION_NAME }}
          success-mention-id: ${{ secrets.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ secrets.SUCCESS_MENTION_NAME }}
          job-status: ${{ steps.check_status.outputs.status }}  # Pass dynamically fetched status
