name: New Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from env.json
        id: load_env
        uses: actions/github-script@v6.3.3
        with:
          script: |
            const fs = require('fs');
            const envFile = 'env.json';
            const data = fs.readFileSync(envFile, 'utf8');
            const env = JSON.parse(data);
            console.log('Parsed environment variables:', env);
            const environment = {
              ERROR_MENTION_ID: env.ERROR_MENTION_ID,
              ERROR_MENTION_NAME: env.ERROR_MENTION_NAME,
              SUCCESS_MENTION_ID: env.SUCCESS_MENTION_ID,
              SUCCESS_MENTION_NAME: env.SUCCESS_MENTION_NAME
            };
            console.log(environment);
            return environment;

      - name: Send notification to Microsoft Teams
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          error-mention-id: ${{ steps.load_env.outputs.ERROR_MENTION_ID }}
          error-mention-name: ${{ steps.load_env.outputs.ERROR_MENTION_NAME }}
          success-mention-id: ${{ steps.load_env.outputs.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ steps.load_env.outputs.SUCCESS_MENTION_NAME }}
