name: 'Simple Workflow'

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Notify
        uses: ./.github/actions/build_and_notify
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          error-mention-id: ${{ secrets.ERROR_MENTION_ID }}
          error-mention-name: ${{ secrets.ERROR_MENTION_NAME }}
          success-mention-id: ${{ secrets.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ secrets.SUCCESS_MENTION_NAME }}
