name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    environment: GHA_Environment_Variables

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: echo "Building"

      - name: Test
        shell: bash
        run: echo "Testing"

      # - name: Error
      #   shell: bash
      #   run: exit 1

      - name: Build and Notify
        uses: ./.github/actions/build_and_notify
        with:
          error-mention-id: ${{ env.ERROR_MENTION_ID }}
          error-mention-name: ${{ env.ERROR_MENTION_NAME }}
          success-mention-id: ${{ env.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ env.SUCCESS_MENTION_NAME }}
