name: New Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse environment variables
        run: |
          echo "ERROR_MENTION_ID='${{ fromJson(toString(file('./env.json')))['ERROR_MENTION_ID'] }}'" >> .env
          echo "ERROR_MENTION_NAME='${{ fromJson(toString(file('./env.json')))['ERROR_MENTION_NAME'] }}'" >> .env
          echo "SUCCESS_MENTION_ID='${{ fromJson(toString(file('./env.json')))['SUCCESS_MENTION_ID'] }}'" >> .env
          echo "SUCCESS_MENTION_NAME='${{ fromJson(toString(file('./env.json')))['SUCCESS_MENTION_NAME'] }}'" >> .env

      - name: Print environment variables
        run: |
          source .env
          echo "ERROR_MENTION_ID: $ERROR_MENTION_ID"
          echo "ERROR_MENTION_NAME: $ERROR_MENTION_NAME"
          echo "SUCCESS_MENTION_ID: $SUCCESS_MENTION_ID"
          echo "SUCCESS_MENTION_NAME: $SUCCESS_MENTION_NAME"

      - name: Send notification to Microsoft Teams
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          error-mention-id: ${{ env.ERROR_MENTION_ID }}
          error-mention-name: ${{ env.ERROR_MENTION_NAME }}
          success-mention-id: ${{ env.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ env.SUCCESS_MENTION_NAME }}
