name: New Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from env.json
        run: |
          echo "::group::Load Environment Variables"
          node -e "const fs = require('fs'); \
                  const envFile = 'env.json'; \
                  const data = fs.readFileSync(envFile, 'utf8'); \
                  const env = JSON.parse(data); \
                  console.log('Parsed environment variables:', env); \
                  console.log(`ERROR_MENTION_ID=${env.ERROR_MENTION_ID}`); \
                  console.log(`ERROR_MENTION_NAME=${env.ERROR_MENTION_NAME}`); \
                  echo "ERROR_MENTION_ID=${env.ERROR_MENTION_ID}" >> $GITHUB_ENV; \
                  echo "ERROR_MENTION_NAME=${env.ERROR_MENTION_NAME}" >> $GITHUB_ENV; \
                  echo "SUCCESS_MENTION_ID=${env.SUCCESS_MENTION_ID}" >> $GITHUB_ENV; \
                  echo "SUCCESS_MENTION_NAME=${env.SUCCESS_MENTION_NAME}" >> $GITHUB_ENV;"
          echo "::endgroup::"

      - name: Send notification to Microsoft Teams
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          error-mention-id: ${{ env.ERROR_MENTION_ID }}
          error-mention-name: ${{ env.ERROR_MENTION_NAME }}
          success-mention-id: ${{ env.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ env.SUCCESS_MENTION_NAME }}
