name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    environment: GHA_Environment_Variables

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        shell: bash
        run: echo "Building"

      - name: Test
        shell: bash
        run: echo "Testing"

      - name: Error
        shell: bash
        run: exit 1

      - name: Build and Notify
        uses: ./.github/actions/build_and_notify
        with:
          error-mention-id: ${{ vars.ERROR_MENTION_ID }}
          error-mention-name: ${{ vars.ERROR_MENTION_NAME }}
          success-mention-id: ${{ vars.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ vars.SUCCESS_MENTION_NAME }}
