name: Simple Workflow   
  
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: echo "Building"

      - name: Test
        shell: bash
        run: echo "Testing"

      # - name: Error  
      #   shell: bash
      #   run: exit 1  

      - name: Checkout repository
        if: always()
        uses: actions/checkout@v2

      - name: Determine Job Status
        id: check_status
        if: always()
        run: |
          echo "Job status: ${{ job.status }}"
          if [ ${{ job.status }} == 'completed' ]; then
            if [ ${{ job.outcome }} == 'success' ]; then
              echo "::set-output name=status::PASS"
            else
              echo "::set-output name=status::FAIL"
            fi
          else
            echo "::set-output name=status::IN_PROGRESS"
          fi

      - name: Notify Build Status
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          error-mention-id: ${{ secrets.ERROR_MENTION_ID }}
          error-mention-name: ${{ secrets.ERROR_MENTION_NAME }}
          success-mention-id: ${{ secrets.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ secrets.SUCCESS_MENTION_NAME }}
          job-status: ${{ steps.check_status.outputs.status }}  # Pass dynamically fetched status
